config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unacceptable', via: :all
  get '/500', to: 'errors#internal_error', via: :all

  resources :countries
  resources :languages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  post '/contact', to: 'static_pages#contact'
  get '/faq', to: 'static_pages#faq'
  get '/privacy-policy', to: 'static_pages#privacy_policy'

  get '/favorites', to: 'favorites#index'

  resources :stations do
    member do
      get 'play'
      get 'playing_now'
      get 'similar'
      get 'thankyou'
    end

    collection do
      get 'player_close'
    end

    resources :reviews, only: %i[new create destroy]
    resources :favorites, only: %i[create destroy]
  end

  resources :categories, path: :genres
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :countries, only: %i[index show]
      resources :languages, only: %i[index show]
      resources :categories, only: %i[index show]
      resources :stations, only: %i[index show]
    end
  end

  root to: 'static_pages#home'
end

app/models/station.rb
class Station < ApplicationRecord
  store_accessor :settings, :dirble_id
  mount_uploader :logo, LogoUploader

  is_impressionable counter_cache: true, unique: true
  enum status: [:pending, :active, :archived]

  has_and_belongs_to_many :categories
  before_destroy { categories.clear }

  has_many :streams, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :language
  belongs_to :country

  paginates_per 15

  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, :country_id, :language_id, presence: true
  before_validation :strip_whitespace

  accepts_nested_attributes_for :streams, reject_if: :all_blank, allow_destroy: true

  delegate :name, to: :country, prefix: true, allow_nil: true
  delegate :title, to: :language, prefix: true, allow_nil: true

  def similar_stations
    Station.active
           .where(country_id: country_id)
           .or(Station.where(language_id: language_id))
           .or(Station.where(categories: categories))
           .where.not(id: id)
           .order(impressions_count: :desc)
           .limit(5)
  end

  def playing_now
    song = active_streams.first.try(:icy_metadata)
    return unless song.present?

    now_playing = song.now_playing
    now_playing.present? ? "Playing Now: #{now_playing}" : country_name
  rescue Errno::EINVAL
    country_name
  end

  def active_streams
    @active_streams ||= streams.active
  end

  def active_reviews
    @active_reviews ||= reviews.active
  end

  def full_address
    @full_address ||= join_array([address, country_name])
  end

  def categories_names
    @categories_names ||= join_array(categories.pluck(:title))
  end

  def meta_title
    @meta_title ||= "Listen to #{name}, #{full_address} | Jharko"
  end

  def meta_desc
    @meta_desc ||= (description? ? description.squish : default_meta_desc)
  end

  def meta_keywords
    @meta_keywords ||= join_array([name, tagline, 'free radio', categories_names, 'stream music', full_address, language_title.to_s + ' radio'].flatten)
  end

  def refresh_reviews_ratings_count
    update(reviews_count: active_reviews.size, average_rating: calc_ar)
  end

  private

  def default_meta_desc
    str = "#{name} is a Radio Station streaming online from #{full_address}. "
    str += "This station plays content of categories - #{categories_names}. " if categories_names.present?
    str += "Listen to #{name} for free."
    str
  end

  def join_array(arr)
    arr.compact.reject(&:empty?).join(', ')
  end

  def strip_whitespace
    name.try(:strip!)
  end

  def calc_ar
    ratings_sum = active_reviews.pluck(:rating).sum
    count = active_reviews.size
    count.zero? ? 0 : (ratings_sum.to_f / count)
  end
end

app/controllers/api/v1/stations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Countries API class
    class StationsController < ApiController
      respond_to :json

      def index
        @stations = Station.order(id: :desc).page params[:page]
      end

      def show
        @station = Station.find params[:id]
      end
    end
  end
end

app/controllers/stations_controller.rb
# frozen_string_literal: true

# Stations Controller
class StationsController < ApplicationController
  include Favoritable

  before_action :authenticate_admin!, except: [:new, :create, :index, :show, :play, :playing_now, :player_close, :similar, :thankyou]
  before_action :set_station, only: [:show, :edit, :update, :destroy, :play, :similar, :playing_now, :thankyou]

  # rescue_from ActiveRecord::RecordNotFound, with: :invalid_station
  # def invalid_station
  #   redirect_to root_path, alert: 'Station not available!'
  # end

  impressionist actions: [:show], unique: [:session_hash]

  # GET /stations
  # GET /stations.json
  def index
    stations = Station.order(updated_at: :desc)

    # Also display pending stations if admin
    stations = stations.active unless user_signed_in? && current_user.is_admin?
    @stations = stations.order(id: :desc).page params[:page]
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    redirect_to root_path, alert: 'Station not available!' unless accessible?

    favorites_button(@station)
    impressionist(@station)
  end

  # GET /stations/new
  def new
    @title = 'Add New Radio Station'
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        # If admin creates a station, redirect to show page.
        # If guest creates a station, redirect to thank you page.
        path = (user_signed_in? && current_user.is_admin?) ? @station : thankyou_station_path(@station)

        format.html { redirect_to path, notice: 'Station was successfully saved.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      begin
        if @station.update(station_params)
          format.html { redirect_to @station, notice: 'Station was successfully updated.' }
          format.json { render :show, status: :ok, location: @station }
        else
          format.html { render :edit }
          format.json { render json: @station.errors, status: :unprocessable_entity }
        end
      rescue => e
        flash.now[:alert] = "<b>Error: </b>#{e}".html_safe
        format.html { render :edit }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def play
    session[:stream] = @station.active_streams.map{ |s| {station_id: @station.id, url: s.url, content_type: (s.content_type.present? ? s.content_type : 'audio/mpeg')} }
  end

  def playing_now
    @playing_now = @station.playing_now
  end

  def player_close
    session[:stream] = nil
  end

  def similar
    @stations = @station.similar_stations.includes(:country)
  end

  # Displays thank you page after guest adds a radio station
  def thankyou; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @station = Station.friendly.find(params[:id])
  end

  def accessible?
    @station.active? || (user_signed_in? && current_user.is_admin?)
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def station_params
    params.require(:station).permit(
      :name, :tagline, :description, :country_id, :language_id, :slug, :logo,
      :website, :twitter, :facebook, :address, :contact, :email,
      category_ids: [],
      streams_attributes: %i[id url _destroy]
    )
  end
end

app/helpers/stations_helper.rb
# frozen_string_literal: true

# Stations Helper module
module StationsHelper
  def google_structured_data station
    data = {
      "@context": 'http://schema.org',
      "@type": 'RadioStation',
      "name": station.name.to_s,
      "url": station_url(station),
      "image": ENV['ROOT_URL'] + station.logo_url,
      "address": station.full_address,
      "telephone": '-'
    }

    if station.active_reviews.any?
      data['aggregateRating'] = {
        "@type": 'AggregateRating',
        "ratingValue": station.average_rating,
        "reviewCount": station.reviews_count
      }
    end
    javascript_tag data.to_json, type: 'application/ld+json'
  end

  def station_thumb(station)
    link_to station, remote: true do
      concat image_tag(station.logo_url, class: 'border img-fluid', alt: station.name)
      concat content_tag('span', station.name)
    end
  end
end

app/views/stations/_display_rating.html.haml
- if station.present? && station.average_rating.positive?
  .rating_stars
    = select_tag :average_rating_field, options_for_select((1..5).to_a), id: "average_rating#{station.id}"
    :javascript
      $("#average_rating#{station.id}").barrating({
        theme: 'fontawesome-stars',
        initialRating: #{station.average_rating},
        readonly: true
      });

app/views/stations/_index.html.haml
- set_meta_tags title: "Radio Stations | Stream Radio Online | Jharko",
                description: 'Find radio stations about sports, news, music and talk.',
                keywords: default_keywords

%h1.h2
  Stations
  = link_to 'New Station', new_station_path, class: 'btn btn-primary float-right' if user_signed_in? && current_user.is_admin?

.table-responsive
  %table.table
    %thead
      %tr
        %th{colspan: 2} Name
        %th Country
        - if user_signed_in? && current_user.is_admin?
          %th Status
          %th
          %th

    %tbody
      - @stations.each do |station|
        %tr
          %td{width: '80'}= image_tag(station.logo_url, class: 'border mr-3', size: '50x50', alt: station.name)
          %td
            %strong= link_to station.name, station
            %div
              %small= station.website
              %div
                - if station.twitter?
                  = link_to 'Twitter', 'https://twitter.com/' + station.twitter.gsub('@', ''), class: 'btn'
                - if station.facebook?
                  = link_to 'Facebook', station.facebook, class: 'btn'
          %td= station.country_name
          - if user_signed_in? && current_user.is_admin?
            %td
              - status_code = { pending: 'primary', active: 'success', archived: 'secondary' }
              %span.badge{class: "badge-#{status_code[station.status.to_sym]}"}= station.status.titleize
            %td= link_to 'Edit', edit_station_path(station)
            %td= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' }

      %tr
        %td.pt-3{colspan: 11}= paginate @stations

app/views/stations/_most_popular.html.haml
- stations.each do |station|
  .media.form-group
    .media-left= image_tag(station.logo_url, class: 'border mr-3', size: '60x60', alt: station.name)
    .media-body
      = link_to station.name, station, remote: true
      %div= station.country_name

app/views/stations/_player.html.haml
- if session[:stream].present?
  - stream = session[:stream].first.symbolize_keys!
  - station = Station.find_by(id: stream[:station_id])
  - if station.present?
    #inner
      .container
        .row
          .col-md-5
            .media
              .align-self-center.mr-3= image_tag station.logo_url, size: '50x50', class: 'border', alt: station.name
              .media-body
                = link_to station.name, station_path(station), remote: true, class: 'text-truncate'
                .small.text-truncate{id: "playing_now#{station.id}"}= station.country_name
                :javascript
                  $.get("#{playing_now_station_path(station)}")
                  if(typeof playingNow !== 'undefined') { clearInterval(playingNow); }
                  playingNow = setInterval(function(){ $.get("#{playing_now_station_path(station)}") }, 60000);

          .col-md-5
            - if stream.present?
              - if (session[:stream].size == 1) && (stream[:content_type] == 'audio/aacp')
                -# Hack for playing aac file
                %audio{controls: true, src: "#{stream[:url]}"}

              - else
                %audio{controls: true, id: 'player', preload: 'none', 'data-plyr-config': '{ "invertTime": false, "toggleInvert": false }'}

            - else
              .small.text-danger
                .fa.fa-exclamation-triangle
                This station doesn't have a valid stream.

          .col-md-2
            = link_to player_close_stations_path, remote: true, title: 'Close Player' do
              .fa.fa-times.mt-08.pull-right.player_close

    :javascript
      player = new Plyr('#player', {
        controls: ['play-large', 'play', 'current-time', 'mute', 'volume']
      });
      player.source = {
        type: 'audio',
        title: "#{station.name}",
        sources: [{
          src: "#{stream[:url].strip}",
          type: "#{stream[:content_type].try(:strip) || 'audio/mpeg'}",
        }]
      };
      player.play();

app/views/stations/_show.html.haml
- set_meta_tags title: @station.meta_title,
                description: @station.meta_desc,
                keywords: @station.meta_keywords,
                og: { title: @station.meta_title,
                  url: station_url(@station),
                  image: image_url(@station.logo_url),
                  description: @station.meta_desc }

= google_structured_data @station

.row
  .col-md-8{itemscope: true, itemtype: 'http://schema.org/RadioStation'}
    %span.d-none{itemprop: 'telephone'} -
    .row
      .col-md-12
        %h5.mb-3.pb-2.border-bottom
          Station Info
          .btn-toolbar.mb-2.float-right
            - if user_signed_in? && current_user.is_admin?
              = link_to 'Edit', edit_station_path(@station), class: 'btn btn-default btn-sm'
              = link_to 'Remove', @station, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-default btn-sm'
            = link_to '< Back', request.headers['HTTP_REFERER'] || root_path, remote: true, class: 'btn btn-default btn-sm'

    .row
      .col-md-3.form-group= image_tag(@station.logo_url, class: 'border img-fluid', alt: @station.name, itemprop: 'image')
      .col-md-9.form-group
        .row
          .col-md-12.form-group
            %h1.h2.font-weight-light{itemprop: 'name'}= @station.name
            - if @station.tagline?
              %div= @station.tagline

            - cnames = @station.categories_names
            %ul.nav.small.lh-25
              - if cnames.present?
                %li.nav-item.text-muted.pr-2= genre_links(cnames) + '&nbsp; |'.html_safe
              %li.nav-item.text-muted.pr-2= "<a href=\"#reviews\">Reviews:</a> #{@station.reviews_count} &nbsp; |".html_safe
              %li.nav-item.text-muted.pr-2= "<a href=\"#average_rating\">Average Rating:</a>".html_safe
              %li.nav-item.text-muted.rating_stars
                - if @station.average_rating.positive?
                  = select_tag :average_rating_field, options_for_select((1..5).to_a)
                  :javascript
                    $('#average_rating_field').barrating({
                      theme: 'fontawesome-stars',
                      initialRating: #{@station.average_rating},
                      readonly: true
                    });
                - else
                  %strong 0.0

        = render 'stream', station: @station

    .row
      .col-md-12
        %h3.h4 Details

    - if @station.description?
      .row
        .col-md-12.form-group{itemprop: 'description'}= @station.description

    .row
      - country = link_to @station.country_name, country_path(@station.country)
      .col-md-12.small Location
      .col-md-12.form-group{itemprop: 'address'}= [@station.address, country].compact.reject(&:empty?).join(', ').html_safe

    - if @station.website?
      .row
        .col-md-12.small Website
        .col-md-12.form-group= link_to @station.website, "http://#{@station.website.gsub('http://', '').gsub('https://', '')}", target: '_blank'
    - if @station.twitter?
      .row
        .col-md-12.small Twitter
        .col-md-12.form-group= @station.twitter
    - if @station.facebook?
      .row
        .col-md-12.small Facebook
        .col-md-12.form-group= @station.facebook
    - if @station.contact?
      .row
        .col-md-12.small Address
        .col-md-12.form-group= @station.contact
    - if @station.email?
      .row
        .col-md-12.small Email
        .col-md-12.form-group= @station.email

    %hr
    = render 'reviews/review', station: @station

  .col-md-4.bg-light.p-3
    %h5.mb-3.pb-2.border-bottom Similar Stations
    %h2.small.pb-2.lh-15 Listen to #{@station.name} live or stream radio stations similar to #{@station.name}.
    #similar_stations
      :javascript
        $.get("#{similar_station_path(@station)}");

app/views/stations/_station.html.haml
.col-md-4.col-sm-6.form-group
  = link_to station_path(station), title: station.name, remote: true do
    .media.border
      = image_tag(station.logo_url, class: 'border-right mr-3', size: '90x90', alt: station.name)
      .media-body.py-2.d-inline-block.pr-2.width-50.text-nowrap.text-truncate
        %h5.mt-0.mb-0.text-nowrap.text-truncate= station.name
        %small.text-muted= station.country_name
        = render 'stations/display_rating', station: station

app/views/stations/_stream.html.haml
.row
  - if station.active_streams.any?
    - stream = station.active_streams.first
    .col-lg-2.form-group= link_to 'Play',  play_station_path(station), remote: true, class: 'btn btn-block btn-outline-danger'
    .col-lg-3.form-group
      %div{id: "favorite#{station.id}"}= render 'favorites/link', station: station, favorite: @favorites_button

    .col-lg-7.form-group
      #sharethis-inline-share-buttons

      - description = station.description || "#{station.name} is a radio station streaming live from #{station.country_name}. Listen to this station and others online at jharko.com."
      :javascript
        window.__sharethis__.load('inline-share-buttons', {
          id: 'sharethis-inline-share-buttons',
          enabled: true,
          networks: ['facebook', 'twitter', 'googleplus', 'pinterest', 'email', 'sharethis', 'sms'],
          show_mobile_buttons: false,
          url: "#{URI.join(root_url, station_path(station))}",
          image: "#{URI.join(root_url, station.logo_url)}",
          description: "#{description.squish}",
          title: "Listen to #{station.name} live"
        });

    #player1
    :javascript
      new Plyr(document.getElementById('player'));

  - else
    .col-md-12.text-danger This station doesn't have any streams.

app/views/stations/edit.html.haml
%h1 Edit - #{@station.name}

= render 'form'

= link_to 'Show', @station
\|
= link_to 'Back', stations_path

app/views/stations/index.html.haml
%h1 Listing stations

.table-responsive
  %table.table
    %thead
      %tr
        %th{colspan: 2} Name
        %th Country
        %th Slug
        %th Total listeners
        - if user_signed_in? && current_user.is_admin?
          %th
          %th

    %tbody
      - @stations.each do |station|
        %tr
          %td= image_tag(station.logo_url, class: 'border-right mr-3', size: '50x50')
          %td
            %strong= link_to station.name, station
            %div
              %small= station.website
              %div
                - if station.twitter?
                  = link_to 'Twitter', station.twitter, class: 'btn'
                - if station.facebook?
                  = link_to 'Facebook', station.facebook, class: 'btn'
          %td= station.country
          %td= station.slug
          %td= station.total_listeners
          - if user_signed_in? && current_user.is_admin?
            %td= link_to 'Edit', edit_station_path(station)
            %td= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' }

      %tr
        %td.pt-3{colspan: 11}= paginate @stations

%br

= link_to 'New Station', new_station_path

app/views/stations/new.html.haml
- title @title
= render 'new'

app/views/stations/play.js.erb
$('#player_area').html("<%=j render 'stations/player' %>").show();

app/views/stations/player_close.js.erb
$('#player_area').html('').fadeOut('slow');

app/views/stations/playing_now.js.erb
$("#playing_now<%= @station.id %>").html("<%= @playing_now %>");

app/views/stations/thankyou.html.haml
%h1.h2 Thank you!

.pt-3
  Thank you for listing your station.
  %br
  %br
  We will review
  and publish your station as soon as possible.
  %br
  In the mean time you
  can enjoy listening to other stations..

.pt-3= link_to 'Find Stations', root_path, class: 'btn btn-danger'