config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unacceptable', via: :all
  get '/500', to: 'errors#internal_error', via: :all

  resources :countries
  resources :languages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  post '/contact', to: 'static_pages#contact'
  get '/faq', to: 'static_pages#faq'
  get '/privacy-policy', to: 'static_pages#privacy_policy'

  get '/favorites', to: 'favorites#index'

  resources :stations do
    member do
      get 'play'
      get 'playing_now'
      get 'similar'
      get 'thankyou'
    end

    collection do
      get 'player_close'
    end

    resources :reviews, only: %i[new create destroy]
    resources :favorites, only: %i[create destroy]
  end

  resources :categories, path: :genres
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :countries, only: %i[index show]
      resources :languages, only: %i[index show]
      resources :categories, only: %i[index show]
      resources :stations, only: %i[index show]
    end
  end

  root to: 'static_pages#home'
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :stations

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/api/v1/languages_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Languages API class
    class LanguagesController < ApiController
      respond_to :json

      def index
        @languages = Language.all
      end

      def show
        language = Language.friendly.find(params[:id])
        @stations = language.stations.active
      end
    end
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Find Radio Stations by Language'
    @languages = Language.all.order(:title)
  end

  def show
    @title = "#{@language.title} Radio Stations"

    active_stations = @language.stations.active.includes(:country)
    @pagy, @stations = pagy(active_stations)

    @most_popular = active_stations.order(impressions_count: :desc).limit(10)
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:title)
    end
end

app/views/languages/_form.html.haml
= form_for @language do |f|
  - if @language.errors.any?
    #error_explanation
      %h2= "#{pluralize(@language.errors.count, "error")} prohibited this language from being saved:"
      %ul
        - @language.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/languages/_index.html.haml
- set_meta_tags title: "Find Radio Stations by Language | Stream Radio Online | Jharko",
                description: 'Find local radio stations by language about sports, news, music and talk.',
                keywords: default_keywords

%h1.h2.mb-3.pb-2.font-weight-light.border-bottom
  By Languages
  - if user_signed_in? && current_user.is_admin?
    = link_to 'New Language', new_language_path, class: 'btn btn-primary float-right'

- if @languages.present?
  .row
    - @languages.in_groups_of(@languages.size/3, false) do |group|
      .col-md-4
        - group.each do |language|
          .form-group
            = link_to language.title, language, remote: true
            - if user_signed_in? && current_user.is_admin?
              = link_to 'Edit', edit_language_path(language)
              = link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' }

- else
  .text-danger No langugages present.

app/views/languages/_show.html.haml
- set_meta_tags title: "#{@language.title} Radio Stations | Stream Radio Online | Jharko",
                description: "Find local radio stations for #{@language.title} about sports, news, music and talk.",
                keywords: "#{@language.title},radio,stream radio,listen radio,jharko,online radio"

%h1.h2.mb-3.pb-2.font-weight-light.border-bottom
  #{@language.title} Radio Stations
  - if user_signed_in? && current_user.is_admin?
    = link_to 'Edit', edit_language_path(@language), class: 'btn btn-primary float-right'
    = link_to 'Back', languages_path, class: 'btn btn-primary float-right'

- if @stations.any?
  .row
    .col-md-8
      .row
        - @stations.each do |station|
          .col-lg-3.col-sm-4.col-xs-6.form-group
            = station_thumb(station)
            %div= station.country_name
            = render 'stations/display_rating', station: station

      = pagy_bootstrap_nav(@pagy).html_safe

    .col-md-4.bg-light.p-3
      %h5.mb-3.pb-2.border-bottom Most Popular for #{@language.title}
      = render 'stations/most_popular', stations: @most_popular

- else
  No stations present.

app/views/languages/edit.html.haml
%h1 Editing language

= render 'form'

= link_to 'Show', @language
\|
= link_to 'Back', languages_path

app/views/languages/index.js.erb
$('main.container').html("<%=j render 'index' %>");
history.pushState({turbolinks: true, url: '<%= languages_path %>'}, null, '<%= languages_path %>');
document.title = '<%= title @title %>';

app/views/languages/new.html.haml
%h1 New language

= render 'form'

= link_to 'Back', languages_path

app/views/languages/show.js.erb
$('main.container').html("<%=j render 'show' %>");
history.pushState({turbolinks: true, url: '<%= language_path(@language) %>'}, null, '<%= language_path(@language) %>');
document.title = '<%= title @title %>';