config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unacceptable', via: :all
  get '/500', to: 'errors#internal_error', via: :all

  resources :countries
  resources :languages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  post '/contact', to: 'static_pages#contact'
  get '/faq', to: 'static_pages#faq'
  get '/privacy-policy', to: 'static_pages#privacy_policy'

  get '/favorites', to: 'favorites#index'

  resources :stations do
    member do
      get 'play'
      get 'playing_now'
      get 'similar'
      get 'thankyou'
    end

    collection do
      get 'player_close'
    end

    resources :reviews, only: %i[new create destroy]
    resources :favorites, only: %i[create destroy]
  end

  resources :categories, path: :genres
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :countries, only: %i[index show]
      resources :languages, only: %i[index show]
      resources :categories, only: %i[index show]
      resources :stations, only: %i[index show]
    end
  end

  root to: 'static_pages#home'
end

app/views/shared/_flash_messages.html.haml
- flash.map do |key, value|
  .alert.alert-dismissable{class: "alert-#{key}"}
    %span.close{'data-dismiss': "alert"} &times;
    #{value}

app/views/shared/_footer.html.haml
%footer.footer
  .container
    .row
      .col-md-8.form-group.pt-3
        Copyright &copy; #{Date.today.year}, All Rights Reserved.
        -# = link_to 'FAQ', faq_path, remote: true, class: 'p-2 text-dark'
        = link_to 'Privacy', privacy_policy_path, title: 'Privacy policy', remote: true, class: 'p-2 text-dark'
        = link_to 'About Us', about_path, title: 'About Us', remote: true, class: 'p-2 text-dark'
        = link_to 'Contact', contact_path, title: 'Contact Us', remote: true, class: 'p-2 text-dark'
        = link_to 'Add Radio Station', new_station_path, title: 'Add radio station', remote: true, class: 'p-2 text-dark'
      .col-md-4.form-group.pt-3.text-md-right
        = link_to 'https://www.facebook.com/Jharko-232404494044355/', title: 'Jharko Facebook Page', target: '_blank' do
          %i.fa.fa-facebook

    %span#player_area= render 'stations/player'
    = render 'cookies_eu/consent_banner'

app/views/shared/_header.html.haml
.d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-white.border-bottom.box-shadow
  %h5.my-0.mr-md-auto.font-weight-normal= link_to 'Jharko', root_path, remote: true, class: 'navbar-brand'
  %nav.my-2.my-md-0.mr-md-3
    = link_to favorites_path, remote: user_signed_in?, class: 'p-2 text-dark' do
      = fa_icon 'heart'
      My Favorites
    = link_to 'By Genre', categories_path, title: 'Find radio stations by Genre', remote: true, class: 'p-2 text-dark'
    = link_to 'By Country', countries_path, title: 'Find radio stations by Country', remote: true, class: 'p-2 text-dark'
    = link_to 'By Language', languages_path, title: 'Find radio stations by Language', remote: true, class: 'p-2 text-dark'
    %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
    .dropdown-menu
      - if user_signed_in?
        .dropdown-item= link_to 'Edit profile', edit_user_registration_path, title: 'Edit Profile', class: 'nav-link'
        .dropdown-item= link_to 'Log out', destroy_user_session_path, title: 'Log out', method: :delete, class: 'nav-link'
      - else
        .dropdown-item= link_to 'Log in', new_user_session_path, title: 'Log in', class: 'nav-link'
        .dropdown-item= link_to 'Sign up', new_user_registration_path, title: 'Sign up', class: 'nav-link'