config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unacceptable', via: :all
  get '/500', to: 'errors#internal_error', via: :all

  resources :countries
  resources :languages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  post '/contact', to: 'static_pages#contact'
  get '/faq', to: 'static_pages#faq'
  get '/privacy-policy', to: 'static_pages#privacy_policy'

  get '/favorites', to: 'favorites#index'

  resources :stations do
    member do
      get 'play'
      get 'playing_now'
      get 'similar'
      get 'thankyou'
    end

    collection do
      get 'player_close'
    end

    resources :reviews, only: %i[new create destroy]
    resources :favorites, only: %i[create destroy]
  end

  resources :categories, path: :genres
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :countries, only: %i[index show]
      resources :languages, only: %i[index show]
      resources :categories, only: %i[index show]
      resources :stations, only: %i[index show]
    end
  end

  root to: 'static_pages#home'
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :stations

  scope :top_level, -> { where(ancestry: nil) }

  extend FriendlyId
  friendly_id :title, use: :slugged

  def children
    Category.where(ancestry: self.id)
  end
end

app/controllers/api/v1/categories_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Countries API class
    class CategoriesController < ApiController
      respond_to :json

      def index
        @categories = Category.order(:title)
      end

      def show
        category = Category.friendly.find(params[:id])
        @stations = category.stations.active
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:title)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @title = "#{@category.title} Radio Stations"

    active_stations = @category.stations.active.includes(:country)
    @pagy, @stations = pagy(active_stations)

    @most_popular = active_stations.order(impressions_count: :desc).limit(10)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :slug)
    end
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :slug
    = f.text_field :slug
  .actions
    = f.submit 'Save'

app/views/categories/_index.html.haml
- set_meta_tags title: "Find Radio Stations by Genre | Stream Radio Online | Jharko",
                description: 'Find local radio stations by genre - such as - Adult Contemporary, Classic Rock, Classical, Hip Hop, Jazz, News and more.',
                keywords: default_keywords

%h1.h2.mb-3.pb-2.font-weight-light.border-bottom
  By Genre
  - if user_signed_in? && current_user.is_admin?
    = link_to 'New Genre', new_category_path, class: 'btn btn-primary float-right'

- if @categories.present?
  .row
    - @categories.in_groups_of(@categories.size/3, false) do |group|
      .col-md-4
        - group.each do |category|
          .form-group
            = link_to category.title, category, remote: true
            - if user_signed_in? && current_user.is_admin?
              = link_to 'Edit', edit_category_path(category)
              = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

- else
  .text-danger No categories present.

app/views/categories/_show.html.haml
- set_meta_tags title: "#{@category.title} Radio Stations | Stream Radio Online | Jharko",
                description: "Listen to #{@category.title} radio radio stations from around the globe.",
                keywords: "#{@category.title},radio,stream radio,listen radio,jharko,online radio"

%h1.h2.mb-3.pb-2.font-weight-light.border-bottom
  #{@category.title} Radio Stations
  - if user_signed_in? && current_user.is_admin?
    = link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary float-right'
    = link_to 'Back', categories_path, class: 'btn btn-primary float-right'

- if @stations.any?
  .row
    .col-md-8
      .row
        - @stations.each do |station|
          .col-lg-3.col-sm-4.col-xs-6.form-group
            = station_thumb(station)
            %div= station.country_name
            = render 'stations/display_rating', station: station

      = pagy_bootstrap_nav(@pagy).html_safe

    .col-md-4.bg-light.p-3
      %h5.mb-3.pb-2.border-bottom Most Popular in #{@category.title}
      = render 'stations/most_popular', stations: @most_popular

- else
  No stations present.

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.js.erb
$('main.container').html("<%=j render 'index' %>");
history.pushState({turbolinks: true, url: '<%= categories_path %>'}, null, '<%= categories_path %>');
document.title = '<%= title @title %>';

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
- title @title
= render 'show'

app/views/categories/show.js.erb
$('main.container').html("<%=j render 'show' %>");
history.pushState({turbolinks: true, url: '<%= category_path(@category) %>'}, null, '<%= category_path(@category) %>');
document.title = '<%= title @title %>';